### ISSUE TITLE
Replace deprecated `dplyr` functions

### ISSUE THREAD

**Issue by andreamazzella** [publichealthengland/hcaidcs#22]
Example - `mf_lag_trend` relies on `dplyr::funs`, which was deprecated in dplyr 0.8.0 and so it will be removed in the future, which will break the `hcaids` function.

Some superseded functions such as `dplyr::mutate_at()` are also used, but probably replacing these is less of a priority.

**Comment by simonthelwall** [comment]
$ git grep -i 'dplyr::funs' -- *.R
R/mf_lag_trend.R:      dplyr::funs(lag_12 = dplyr::lag(., 12))
R/mf_lag_trend.R:      dplyr::funs(sum_3 = suppressWarnings(RcppRoll::roll_sum(., 3, align = "right", fill = "NA")))
R/mf_lag_trend.R:      dplyr::funs(lag_3 = dplyr::lag(., 12))
R/mf_lag_trend.R:      dplyr::funs(sum_12 = suppressWarnings(RcppRoll::roll_sum(., 12, align = "right", fill = "NA")))
R/mf_lag_trend.R:      dplyr::funs(lag_12 = dplyr::lag(., 12))

**Comment by simonthelwall** [comment]
Also 

Warning (test-month_to_string.R:17:3): fmonth_to_string works in a mutate chain
`tbl_df()` was deprecated in dplyr 1.0.0.
i Please use `tibble::as_tibble()` instead.

**Comment by simonthelwall** [comment]
Warning (test-aec_age_trends_pc.R:6:3): aec_age_trends_pc returns a ggplot object
`guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead.

**Comment by simonthelwall** [comment]
Thanks @andreamazzella Let me know if you find anything eslse.
