### ISSUE TITLE
Create insert_cols function

### ISSUE THREAD

**Issue by simonthelwall** [publichealthengland/hcaidcs#6]
to simplify following code
```r
denom_pos <- which(names(table4a) == "reporting_organisation")

table4a <- data.frame(table4a[1:denom_pos], insert, table4a[(denom_pos+1):ncol(table4a)])
```

where `insert` is a dataframe of same n rows as table4a

**Comment by piotrpatrzylas** [comment]
library(tibble)
table4a <- add_column(.data = table4a, ... = insert, .after = "reporting_organisation")

**Comment by simonthelwall** [comment]
Thanks Piotr, that's really helpful to know about.
